spring.application.name=Taller
spring.datasource.url=jdbc:mysql://localhost:3306/Taller
spring.datasource.username=autogroup
spring.datasource.password=autogroup_wo

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


#spring.security.user.name=omayma
#spring.security.user.password=1234
